/**
 * Generator — creates thinking pattern files from steps.
 * Part of thinking-patterns — nakprc edition.
 */

import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

function topicToSlug(topic) {
  return topic
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60) || 'thinking'
}

function resolveOutputDir(config, topic) {
  if (config.output?.dir) return config.output.dir
  return `./${topicToSlug(topic)}`
}

/** Render the markdown template for a single step */
function renderStep(step, stepIndex, totalSteps, pattern, config) {
  const template = `---
pattern: ${pattern.label}
step: ${step.id}
step_number: ${stepIndex + 1}
total_steps: ${totalSteps}
generated_at: ${new Date().toISOString()}
---

# Step ${stepIndex + 1}: ${step.label}

> ${step.desc}

## What the AI Did

${step.whatDone}

## Thinking Pattern

${step.thinkingPattern}

## Key Insight

${step.keyInsight}

## Summary

${step.content}
`

  if (config.output?.includeSummary) {
    const summary = config.output.summaryLength === 'long'
      ? step.content
      : config.output.summaryLength === 'medium'
        ? step.content.slice(0, 300)
        : step.content.split('.').slice(0, 2).join('.') + '.'
  }

  return template
}

/** Generate sequential thinking pattern files */
export function generateFiles(steps, pattern, config, topic) {
  const outputDir = resolveOutputDir(config, topic)
  const filePrefix = config.output?.filePrefix || 'think'
  const naming = config.output?.naming || 'numbered'
  const fileExtension = config.output?.fileExtension || 'md'
  const files = []

  mkdirSync(outputDir, { recursive: true })

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i]
    const ext = fileExtension || 'md'

    let fileName
    if (naming === 'named') {
      fileName = `${filePrefix}-${step.id}.${ext}`
    } else if (naming === 'datetime') {
      const dt = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
      fileName = `${filePrefix}-${dt}-${step.id}.${ext}`
    } else {
      // numbered: 1, 2, 3, 4...
      fileName = `${filePrefix}${i + 1}.${ext}`
    }

    const filePath = join(outputDir, fileName)
    const content = renderStep(step, i, steps.length, pattern, config)

    writeFileSync(filePath, content, 'utf8')
    files.push({ path: filePath, name: fileName, step: step.label, stepNumber: i + 1 })
  }

  const indexContent = `# Thinking Patterns: ${topic}\n\n` +
    `Generated: ${new Date().toISOString()}\n` +
    `Pattern: ${pattern.label}\n` +
    `Output: ${outputDir}\n` +
    `Total Steps: ${steps.length}\n\n` +
    `## Files\n\n` +
    files.map((f) => `- [${f.name}](./${f.name}) — Step ${f.stepNumber}: ${f.step}`).join('\n') +
    `\n\n---\n*Generated by thinking-patterns — nakprc*\n`

  writeFileSync(join(outputDir, `index.${fileExtension || 'md'}`), indexContent, 'utf8')
  files.push({ path: join(outputDir, `index.${fileExtension || 'md'}`), name: `index.${fileExtension || 'md'}`, step: 'Index', stepNumber: 0 })

  return files
}
